# Generated by Django 5.2 on 2025-04-09 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=65, unique=True)),
                ("description", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Prepared", "Prepared"),
                            ("Paid", "Paid"),
                            ("Canceled", "Canceled"),
                        ],
                        default="Pending",
                        max_length=8,
                    ),
                ),
                ("url_payment", models.URLField(blank=True, max_length=400, null=True)),
                ("is_anonymous", models.BooleanField(default=False)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "donator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Dream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("to_another", models.BooleanField(default=False)),
                ("content", models.TextField()),
                (
                    "goal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("photo", models.URLField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Application", "Application"),
                            ("Active", "Active"),
                            ("Completed", "Completed"),
                        ],
                        default="Application",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "stripe_product_id",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        default=[],
                        related_name="dreams",
                        to="dreams.category",
                    ),
                ),
                (
                    "comments",
                    models.ManyToManyField(
                        blank=True,
                        default=[],
                        related_name="dreams",
                        to="dreams.comment",
                    ),
                ),
                (
                    "donations",
                    models.ManyToManyField(
                        blank=True,
                        default=[],
                        related_name="dreams",
                        to="dreams.donation",
                    ),
                ),
                (
                    "dreamer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.dreamerprofile",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="donation",
            name="dream",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="donations_set",
                to="dreams.dream",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="dream",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dreams.dream"
            ),
        ),
    ]
