# Generated by Django 5.2 on 2025-04-09 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dreams", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="donator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dream",
            name="categories",
            field=models.ManyToManyField(
                blank=True, default=[], related_name="dreams", to="dreams.category"
            ),
        ),
        migrations.AddField(
            model_name="dream",
            name="comments",
            field=models.ManyToManyField(
                blank=True, default=[], related_name="dreams", to="dreams.comment"
            ),
        ),
        migrations.AddField(
            model_name="dream",
            name="donations",
            field=models.ManyToManyField(
                blank=True, default=[], related_name="dreams", to="dreams.donation"
            ),
        ),
        migrations.AddField(
            model_name="dream",
            name="dreamer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.dreamerprofile",
            ),
        ),
        migrations.AddField(
            model_name="dream",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="dream",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="donations_set",
                to="dreams.dream",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="dream",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dreams.dream"
            ),
        ),
    ]
