# Generated by Django 5.2 on 2025-04-09 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dreams", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dream",
            name="number_views",
            field=models.IntegerField(default=0),
        ),
    ]
