# Generated by Django 5.2 on 2025-04-11 01:10

import easy_thumbnails.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dreams", "0003_dream_number_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dream",
            name="photo",
            field=easy_thumbnails.fields.ThumbnailerImageField(
                blank=True, null=True, upload_to=""
            ),
        ),
    ]
