# Generated by Django 5.2 on 2025-04-11 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dreams", "0004_alter_dream_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dream",
            name="photo",
        ),
        migrations.AddField(
            model_name="dream",
            name="photo_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dream",
            name="thumbnail_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
