# Generated by Django 5.2 on 2025-04-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dreams", "0006_remove_dream_comments_remove_dream_donations_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dream",
            name="title",
            field=models.CharField(max_length=45),
        ),
    ]
