# Generated by Django 5.2.1 on 2025-05-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dreams", "0008_follower"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="status",
            field=models.CharField(
                choices=[
                    ("Prepared", "Prepared"),
                    ("Paid", "Paid"),
                    ("Canceled", "Canceled"),
                ],
                default="Prepared",
                max_length=8,
            ),
        ),
    ]
