# Generated by Django 5.2.1 on 2025-05-27 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dreams", "0009_alter_donation_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="donation",
            options={"ordering": ["-date"]},
        ),
    ]
