# Generated by Django 5.2.1 on 2025-06-10 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dreams", "0010_alter_donation_options"),
        ("user_profile", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="dream",
            name="dreamer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user_profile.dreamerprofile",
            ),
        ),
        migrations.AlterField(
            model_name="dream",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dreams",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
