# Generated by Django 5.2.1 on 2025-06-29 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dreams", "0011_alter_dream_dreamer_alter_dream_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
