# Generated by Django 5.2.1 on 2025-06-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_othercountry"),
    ]

    operations = [
        migrations.AddField(
            model_name="othercountry",
            name="code",
            field=models.CharField(default=None, max_length=2, unique=True),
            preserve_default=False,
        ),
    ]
