# Generated by Django 5.2.1 on 2025-06-28 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_othercountry_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="othercountry",
            options={"ordering": ["name"], "verbose_name_plural": "other countries"},
        ),
        migrations.AlterField(
            model_name="dreamerprofile",
            name="city",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="profiles.city",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="profiles.city",
            ),
        ),
        migrations.AddConstraint(
            model_name="city",
            constraint=models.UniqueConstraint(
                fields=("name", "country"), name="unique_city_country"
            ),
        ),
    ]
