# Generated by Django 5.2 on 2025-04-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dreamerprofile",
            name="is_collective",
            field=models.BooleanField(default=False),
        ),
    ]
