# Generated by Django 5.2 on 2025-04-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_dreamerprofile_is_collective"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_collective",
            field=models.BooleanField(default=False),
        ),
    ]
