# Generated by Django 5.2 on 2025-04-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_subscriber"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriber",
            options={"ordering": ["email"]},
        ),
        migrations.AddField(
            model_name="subscriber",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
