# Generated by Django 5.2 on 2025-04-14 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_subscriber_options_subscriber_is_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="avatar",
            new_name="avatar_url",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="thumbnail_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
