# Generated by Django 5.2.1 on 2025-06-10 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dreams", "0011_alter_dream_dreamer_alter_dream_owner"),
        ("users", "0008_rename_avatar_userprofile_avatar_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="city",
            name="country",
        ),
        migrations.RemoveField(
            model_name="dreamerprofile",
            name="city",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="city",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
        migrations.DeleteModel(
            name="Country",
        ),
        migrations.DeleteModel(
            name="DreamerProfile",
        ),
        migrations.DeleteModel(
            name="City",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
